-- 1) I would like to know how many signal lights exist within a 5m radius of elementary school x.
SELECT DISTINCT POLE_ID FROM POLE WHERE NEAR_SCHOOL = 1;

-- 2) I would like to know how many street lights have traffic signals on them.
SELECT DISTINCT POLE_ID, POLE_LAT, POLE_LONG FROM POLE WHERE IS_TRAFFIC_POLE = 1;

-- 3) I would like to know which streetlights haven’t had any maintenance updates in the last 3 years. 
SELECT DISTINCT POLE.POLE_ID, MAINT_RECORD.MAINT_RECORD_DATE, POLE.POLE_HGT, POLE.POLE_LAT, POLE.POLE_LONG
FROM POLE
JOIN MAINT_RECORD
ON MAINT_RECORD.POLE_ID = POLE.POLE_ID
WHERE MAINT_RECORD.IS_SERVICE = 1 AND MAINT_RECORD.MAINT_RECORD_DATE < '2018-01-01 00:00:00'

-- 4) I would like to find out which technician creates the maintenance report for the streetlight on street X at the coordinates (lambda, phi).
--SELECT EM_ID FROM MAINT_REPORT IN (SELECT DISTINCT POLE_ID, X_COORDINATE, Y_COORDINATE FROM POLE WHERE POLE_TYPE = STREETLIGHT, X_COORDINATE = (given coordinate), Y_COORDINATE = (given coordinate))
SELECT MAINT_RECORD.EMPLOYEE_ID, EMPLOYEE.EMPLOYEE_FNAME, EMPLOYEE.EMPLOYEE_LNAME, POLE_LAT, POLE_LONG
FROM MAINT_RECORD
JOIN EMPLOYEE
ON MAINT_RECORD.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
JOIN POLE
ON POLE.POLE_ID = MAINT_RECORD.POLE_ID
WHERE (POLE_LAT = 49.02922429) AND (POLE_LONG = -122.8010562);


-- 5) I would like to get a count on the total of the inspected streetlights for the year of 2019.
--SELECT COUNT(DISTINCT POLE_ID) FROM MAINTENANCE_REPORT WHERE MAINTENANCE_REPORT.MAINT_DATE = 2019, POLE_TYPE = STREETLIGHT;
SELECT COUNT(MAINT_RECORD.MAINT_RECORD_DATE) AS [MAINTENANCE COUNT]
FROM MAINT_RECORD
WHERE	MAINT_RECORD.MAINT_RECORD_DATE >= '2019-01-01 00:00:00' 
			AND MAINT_RECORD.MAINT_RECORD_DATE <=  '2019-12-31 11:59:59'