-- DATABASE PROJECT

USE MASTER;

IF DB_ID(N'WHITEROCK_STREETLIGHT') IS NOT NULL
DROP DATABASE WHITEROCK_STREETLIGHT;
GO
CREATE DATABASE WHITEROCK_STREETLIGHT;
GO

-- Verify database files and size
SELECT NAME, SIZE, SIZE*1.0/128 AS [SIZE IN MBs]
FROM SYS.MASTER_FILES
WHERE NAME = N'WHITEROCK STRETLIGHT'

USE WHITEROCK_STREETLIGHT;

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID INT UNIQUE NOT NULL,
	EMPLOYEE_FNAME VARCHAR(50) NOT NULL,
	EMPLOYEE_LNAME VARCHAR(50) NOT NULL,
	EMPLOYEE_TYPE CHAR(1),
	PRIMARY KEY(EMPLOYEE_ID)
);

CREATE TABLE POLE
(
    POLE_ID 		INTEGER     PRIMARY KEY,
    NEAR_BUSSTOP 	BIT			NOT NULL,
    NEAR_SCHOOL 	BIT			NOT NULL,
    NEAR_PARK 		BIT			NOT NULL,
    NEAR_SIDEWALK 	BIT			NOT NULL,
    IS_TRAFFIC_POLE BIT			NOT NULL,
    IS_LIGHT_POLE	BIT			NOT NULL,
    POLE_STYLE 		VARCHAR(20),
	POLE_BASE 		VARCHAR(20),
	POLE_HGT 		DECIMAL(4, 2),
    POLE_LAT    	FLOAT(20)   NOT NULL    	CHECK(POLE_LAT >= 49.0 and POLE_LAT  <= 49.1),
    POLE_LONG   	FLOAT(20)   NOT NULL    	CHECK(POLE_LONG >= -122.7 and POLE_LONG <= -123.0),
    
    PRIMARY KEY(POLE_ID),
    CONSTRAINT POLE_LOCATION UNIQUE(POLE_LONG, POLE_LAT)
 );

CREATE TABLE T_POLE 
(
	POLE_ID INT NOT NULL,
	T_POLE_BUTT VARCHAR(20),
	T_POLE_SIGN VARCHAR(20),
	
	PRIMARY KEY(POLE_ID)
	FOREIGN KEY(POLE_ID) REFERENCES POLE(POLE_ID)
);

CREATE TABLE L_POLE 
(
	POLE_ID INT,
	L_POLE_BULB_TYPE VARCHAR(20),
	L_POLE_LUMINARE VARCHAR(20)
	
	PRIMARY KEY(POLE_ID)
	FOREIGN KEY(POLE_ID) REFERENCES POLE(POLE_ID)
);


CREATE TABLE UPDATE_HISTORY 
(
	UPDATE_TIMESTAMP SMALLDATETIME DEFAULT(GETDATE()) NOT NULL, -- !!!! CHECK IF THIS IS CORRECT
	POLE_ID INT NOT NULL,
	EMPLOYEE_ID INT NOT NULL,
	
	PRIMARY KEY(UPDATE_TIMESTAMP, POLE_ID),
	FOREIGN KEY(POLE_ID) REFERENCES POLE(POLE_ID)
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);


CREATE TABLE MAINT_RECORD 
(
	MAINT_ID 			INTEGER NOT NULL UNIQUE,
	POLE_ID 			INTEGER NOT NULL,
	EMPLOYEE_ID 		INTEGER NOT NULL,
	MAINT_RECORD_DATE 	DATE 	NOT NULL,
	IS_REINSTALL 		BIT		NOT NULL,
    IS_ASSESSMENT 		BIT		NOT NULL,
	MAINT_ESTIMATED_AGE INT,
	
	PRIMARY KEY(MAINT_ID),
	FOREIGN KEY(POLE_ID) REFERENCES POLE(POLE_ID) ON UPDATE CASCADE,
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES FIELD_TECH(EMPLOYEE_ID) ON UPDATE CASCADE
);


CREATE TABLE MAINT_REINSTALL 
(
	MAINT_ID INTEGER NOT NULL UNIQUE,
	MAINT_RELAMP_DATE DATE,
	MAINT_REPAINT_DATE DATE,

	PRIMARY KEY(MAINT_ID),
	FOREIGN KEY(MAINT_ID) REFERENCES MAINT_RECORD(MAINT_ID) ON UPDATE CASCADE
);

CREATE TABLE MAINT_CONDITITON
(
	MAINT_ID INTEGER NOT NULL UNIQUE,
	MAINT_HAMMER_TEST_RESULT INT,
	MAINT_VISUAL_RUST VARCHAR(10),
	MAINT_LUMINAIRE_COND VARCHAR(20),
	MAINT_ANCHOR_BOLTS_COND VARCHAR(20),
	MAINT_PANEL_COND VARCHAR(20),
	
	PRIMARY KEY(MAINT_ID),
	FOREIGN KEY(MAINT_ID) REFERENCES MAINT_RECORD(MAINT_ID) ON UPDATE CASCADE
);



