-- DATABASE PROJECT

USE MASTER;

IF DB_ID(N'WHITEROCK_STREETLIGHT') IS NOT NULL
DROP DATABASE WHITEROCK_STREETLIGHT;
GO
CREATE DATABASE WHITEROCK_STREETLIGHT;
GO
-- Verify database files and size
SELECT NAME, SIZE, SIZE*1.0/128 AS [SIZE IN MBs]
FROM SYS.MASTER_FILES
WHERE NAME = N'WHITEROCK STRETLIGHT'

USE WHITEROCK_STREETLIGHT;

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID INT UNIQUE NOT NULL,
	USER_FNAME VARCHAR(50) NOT NULL,
	USER_LNAME VARCHAR(50) NOT NULL,
	USER_TYPE CHAR(1),
	PRIMARY KEY(EMPLOYEE_ID)
);

CREATE TABLE FIELD_TECH 
(
	EMPLOYEE_ID INT UNIQUE NOT NULL,
	FIELD_TECH_ID INT UNIQUE NOT NULL,
	FIELD_TECH_CRED VARCHAR(50),
	FIELD_TECH_AREA VARCHAR(50),
	PRIMARY KEY(EMPLOYEE_ID),
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE ENGINEER (
	EMPLOYEE_ID INT UNIQUE NOT NULL,
	ENGINEER_ID INT UNIQUE NOT NULL,
	ENGINEER_CRED VARCHAR(50),
	PRIMARY KEY(EMPLOYEE_ID),
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE MANAGER 
(
	EMPLOYEE_ID INT UNIQUE NOT NULL,
	MANAGER_ID INT UNIQUE NOT NULL,
	MANAGER_CRED VARCHAR(50),
	PRIMARY KEY(EMPLOYEE_ID),
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE PLANNER 
(
	EMPLOYEE_ID INT UNIQUE NOT NULL,
	PLANNER_ID INT UNIQUE NOT NULL,
	PLANNER_CRED VARCHAR(50),
	PRIMARY KEY(EMPLOYEE_ID),
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE POLE
(
    POLE_ID        INTEGER        PRIMARY KEY,
    USERS_ID    INTEGER        NOT NULL    UNIQUE,
    MAINT_YR    INTEGER        DEFAULT 0    NOT NULL    CHECK(MAINT_YR >= 0), 
    POLE_TYPE    VARCHAR(25)    NOT NULL,
    POLE_LAT    FLOAT(20)    NOT NULL    CHECK(POLE_LAT >= -90 and POLE_LAT  <= 90),
    POLE_LONG    FLOAT(20)    NOT NULL    CHECK(POLE_LONG >= -180 and POLE_LONG <= 180),
    FOREIGN KEY(USERS_ID)REFERENCES EMPLOYEE ON UPDATE CASCADE,
    CONSTRAINT POLE_LOCATION UNIQUE(POLE_LONG, POLE_LAT));

CREATE TABLE T_POLE 
(
	POLE_ID INT NOT NULL,
	T_POLE_BUTT VARCHAR(20),
	T_POLE_SIGN VARCHAR(20),
	T_POLE_SIG_DIR VARCHAR(20)
);

CREATE TABLE L_POLE 
(
	POLE_ID INT,
	L_POLE_BULB_TYPE VARCHAR(20),
	L_POLE_STYLE VARCHAR(20),
	L_POLE_BASE VARCHAR(20),
	L_POLE_HGT DECIMAL(4, 2),
	L_POLE_LUMINARE VARCHAR(20)
);


CREATE TABLE UPDATE_HISTORY 
(
	UPDATE_TIMESTAMP DATE DEFAULT SYSDATETIME() NOT NULL,
	POLE_ID INT NOT NULL,
	EMPLOYEE_ID INT NOT NULL,
	PRIMARY KEY(UPDATE_TIMESTAMP, POLE_ID),
	FOREIGN KEY(POLE_ID) REFERENCES POLE(POLE_ID)
);


CREATE TABLE MAINT_RECORD 
(
	MAINT_ID INTEGER NOT NULL UNIQUE,
	POLE_ID INTEGER NOT NULL,
	FIELD_TECH_ID INTEGER NOT NULL,
	MAINT_YEAR INTEGER NOT NULL,
	MAINT_RELAMP_DATE DATETIME,
	MAINT_REPAINT_DATE DATETIME,
	MAINT_HAMMER_TEST_RESULT VARCHAR(12),
	MAINT_VISUAL_RUST VARCHAR(10),
	MAINT_LUMINAIRE_COND VARCHAR(14),
	MAINT_ANCHOR_BOLTS_COND VARCHAR(14),
	MAINT_ESTIMATED_AGE INT,
	PRIMARY KEY(MAINT_ID),
	FOREIGN KEY(POLE_ID) REFERENCES POLE ON UPDATE CASCADE,
	FOREIGN KEY(FIELD_TECH_ID) REFERENCES FIELD_TECH ON UPDATE CASCADE
);